import { useEffect, useState } from 'react';
import { View, Text, TextInput, Pressable, StyleSheet, KeyboardAvoidingView, Platform, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@timely/design';
import { authClient, signInApple, signInGoogle } from './auth';
export function SignIn() {
  const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [cooldown, setCooldown] = useState(0);
  useEffect(() => { if (!cooldown) return; const timer = setTimeout(() => setCooldown(cooldown - 1), 1000); return () => clearTimeout(timer); }, [cooldown]);
  async function run(action: () => Promise<void>) { setBusy(true); setMessage(''); try { await action(); } catch (e) { const code = (e as { code?: string }).code; setMessage(code === 'ERR_REQUEST_CANCELED' ? 'Sign-in cancelled.' : e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } }
  async function send() { const result = await authClient.emailOtp.sendVerificationOtp({ email, type: 'sign-in' }); if (result.error) throw new Error(result.error.message); setSent(true); setCooldown(60); setMessage('Your code expires in 5 minutes.'); }
  const action = (label: string, fn: () => Promise<void>, disabled = false) => <Pressable accessibilityRole="button" disabled={busy || disabled} style={s.button} onPress={() => run(fn)}><Text style={s.buttonText}>{label}</Text></Pressable>;
  return <SafeAreaView style={s.screen}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={s.screen}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.logo}>timely ✳</Text><Text style={s.title}>A little space for what matters.</Text><Text style={s.body}>Your plans, at your pace.</Text><View style={s.card}><Text style={s.heading}>Welcome to your day</Text>{action('Continue with Google', signInGoogle)}{action('Continue with Apple', signInApple)}<Text style={s.body}>or use your email</Text><Text style={s.label}>Email address</Text><TextInput accessibilityLabel="Email address" value={email} onChangeText={setEmail} editable={!sent} autoCapitalize="none" keyboardType="email-address" autoComplete="email" style={s.input}/>{sent && <><Text style={s.label}>Six-digit code</Text><TextInput accessibilityLabel="Six-digit code" value={otp} onChangeText={setOtp} maxLength={6} keyboardType="number-pad" autoComplete="one-time-code" style={s.input}/></>}{action(sent ? 'Sign in' : 'Send me a code', sent ? async () => { const result = await authClient.signIn.emailOtp({ email, otp }); if (result.error) throw new Error(result.error.message); } : send)}{sent && <>{action(cooldown ? `Resend in ${cooldown}s` : 'Resend code', send, cooldown > 0)}{action('Change email', async () => { setSent(false); setOtp(''); })}</>}<Text accessibilityLiveRegion="polite" style={s.body}>{busy ? 'Just a moment…' : message}</Text></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 24, gap: 24 }, logo: { fontFamily: 'Baloo2', color: colors.primary, fontSize: 36 }, title: { fontFamily: 'Baloo2', color: colors.text, fontSize: 40 }, heading: { fontFamily: 'Baloo2', fontSize: 28, color: colors.text }, body: { fontFamily: 'NunitoSans', fontSize: 16, color: colors.muted }, label: { fontFamily: 'NunitoSans', color: colors.text, fontSize: 16 }, card: { backgroundColor: colors.surface, borderRadius: 32, padding: 24, gap: 16 }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.muted, borderRadius: 12, padding: 12, fontFamily: 'NunitoSans', fontSize: 16, color: colors.text }, button: { minHeight: 48, backgroundColor: colors.primary, padding: 16, borderRadius: 18, alignItems: 'center' }, buttonText: { color: colors.surface, fontFamily: 'NunitoSans', fontSize: 16 } });
